name: Pearson-PyTorch
channels:
  - intel
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - scikit-learn
  - pytorch
  - torchvision
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - pillow
  - pip:
      - torchsummary
      - keras
      - tensorflow
      - allennlp
